# Generated by Django 4.2 on 2023-04-09 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aboutus_carouselitem_faq_policy_shipping_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
            preserve_default=False,
        ),
    ]
