# Generated by Django 4.2 on 2023-04-09 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_carouselitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='carousel_items',
        ),
        migrations.AddField(
            model_name='specification',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='api.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LandingPage',
        ),
    ]
