# Generated by Django 4.2 on 2023-04-09 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_product_specifications_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='section',
            name='product',
        ),
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(default=1, upload_to='carousel/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SectionProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.section')),
            ],
        ),
    ]
