# Generated by Django 4.2 on 2023-04-09 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_name_section_title_remove_section_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.section'),
        ),
        migrations.AddField(
            model_name='product',
            name='showcase',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SectionProducts',
        ),
    ]
